[package]
name = "kos"
version = "0.1.0"
authors = ["Kitsu <mail@kitsu.me>", "Sweetbread"]
edition = "2021"

[[example]]
name = "hwa"
path = "examples/hwa.rs"

[[example]]
name = "con"
path = "examples/con.rs"

[[example]]
name = "dark"
path = "examples/dark.rs"

[[example]]
name = "fs_demo"
path = "examples/fs_demo.rs"

[profile.release]
opt-level = "z"
lto = "thin"
panic = "abort"

[profile.dev]
panic = "abort"
